spring.application.name=hotel-management-backend
server.port=8080

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=hotel_mgt;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=1234
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

app.jwt.secret=TXlTdXBlclNlY3JldEtleUZvckpXVFNpZ25pbmdBbmRUb2tlbkdlbmVyYXRpb24xMjM0NTY=
app.jwt.expiration-ms=86400000

app.payroll.overtime-multiplier=1.5
app.payroll.max-paid-leaves=5
